# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "rrna_extraction"
description: Extraction of specific cmsearch-identified rRNA sequences from a fasta file using EASEL
keywords:
  - rRNA
  - fasta
  - easel
  - amplicon
  - cmsearch
  - covariance models
components:
  - infernal/cmsearch
  - cmsearchtbloutdeoverlap
  - easel/eslsfetch
  - extractcoords
input:
  - ch_fasta:
      type: file
      description: |
        The input channel containing the fasta files
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fasta, fasta.gz, fa, fa.gz}"
  - rfam:
      type: file
      description: |
        The input file containing Rfam database for use with cmsearch
        Structure: path(cm)
      pattern: "*.cm"
  - claninfo:
      type: file
      description: |
        The input file containing the claninfo to use for cmsearchtbloutdeoverlap
        Structure: path(claninfo)
      pattern: "*.claninfo"
output:
  - cmsearch_deoverlap_out:
      type: file
      description: |
        Channel containing cmsearchdeoverlap files
        Structure: [ val(meta), path(deoverlapped) ]
      pattern: "*.deoverlapped"
  - easel_out:
      type: file
      description: |
        Channel containing extracted rRNA fasta files
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.fasta"
  - ssu_fasta:
      type: file
      description: Fasta file containing the SSU sequences
      pattern: "*.fasta"
  - lsu_fasta:
      type: file
      description: Fasta file containing the LSU sequences
      pattern: "*.fasta"
  - concat_ssu_lsu_coords:
      type: file
      description: Space-separated concatenated file of coordinates of matches of both SSU and LSU
      pattern: "*.txt"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@chrisata"
