---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "mapseq"
description: Perform taxonomic classification of rRNA reads using reference databases
keywords:
  - taxonomy
  - reads
  - otu
  - rRNA
tools:
  - "mapseq":
      description: "Open source metagenomic 16S/18S read classifier enabling comparative metagenomics."
      documentation: https://github.com/jfmrod/MAPseq
      doi: "10.1093/bioinformatics/btx517"
      licence: "['dual-licensed under GPL v3+ or BSD 2-clause']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - subunit_reads:
      type: file
      description: FASTA file containing rRNA gene reads
      pattern: "*.{fa,fasta}"
  - db_fasta:
      type: file
      description: Reference database FASTA file
      pattern: "*.{fa,fasta}"
  - db_tax:
      type: file
      description: Reference database OTU classifications file
      pattern: "*.txt"
  - db_mscluster:
      type: file
      description: Reference database OTU pre-clustering file
      pattern: "*.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - mseq:
      type: file
      description: Read classification output file
      pattern: "*.mseq"

authors:
  - "@chrisata"
